_cider-ci_include: .cider-ci/shared/defaults.yml

tasks: 
- name: Sleep
  scripts:
    main: 
      body: sleep 3 && echo "done sleeping" 

dependencies:
- type: job
  name: "Dependencies and Triggers Prerequisite"
  states: [passed]
triggers: 
- type: job.updated
  name: "Dependencies and Triggers Prerequisite"
  states: [passed]

