executions:

  "Attachments-Demo": 
    description: |
      This execution demonstrates the usage of the `tree_attachments` and
      `trial_attachments` directive.  It creates a file which is then attached
      as a tree- as well as a trial-attachment. 
    specification:
      name: Attachments Demo
      _cider-ci_include: /.cider-ci/shared/defaults.yml
      tasks:
        _cider-ci_include: /.cider-ci/tasks/attachments.yml

  "Chain-Prerequisite-Demo": 
    description: |
      This one serves as a prerequisite to the "Chain-Dependent-Demo".
    specification: 
      name: Chain-Prerequisite-Demo
      _cider-ci_include: /.cider-ci/shared/sleeping_task_context.yml

  "Chain-Dependent-Demo": 
    description: |
      This demo can only be started if the "Chain-Prerequisite-Demoe" has
      passed. There is also a trigger which will start this demo when
      the prerequisite has finished and the commit is part of the head of
      a brach matching the given regular expression. 
    specification: 
      name: Chain-Dependent-Demo
      _cider-ci_include: /.cider-ci/shared/sleeping_task_context.yml
    depends:
      executions:
        "Chain-Prerequisite-Demo": passed
        "Trigger-Demo": passed
    trigger: true

  "Environment-Variables-Demo": 
    description: |
      This execution Demonstrates the usage of the `environment_variables`
      directive.  It specifies a tasks which lists the environment variables
      with `env | sort`. 
    specification:
      name: Environment Variables Demo
      _cider-ci_include: /.cider-ci/shared/defaults.yml
      task_defaults:
        environment_variables:
          CI_TASK_DEFAULTS: "Inherited!"
      tasks:
        _cider-ci_include: /.cider-ci/tasks/environment_variables.yml

  "Exclusive-Resources-Demo": 
    description: |
      This execution demonstrates the `exclusive_resources` directive.
      Two tasks declare exclusive access to `/tmp/timestamps.log`.  The
      `eager_trials` directive is used to generate effectively four trials.  At
      any time at **most one** trial is _executing_. This can be verified by
      the timestamps in the attachments. 
    specification: 
      _cider-ci_include: /.cider-ci/shared/exclusive_resources_context.yml

  "Info": 
    description: |
      This execution runs a few tasks which show various information, e.g.
      `ls`, `git log`, ...
    specification:
      name: Show info
      _cider-ci_include: /.cider-ci/shared/defaults.yml
      tasks:
        _cider-ci_include: /.cider-ci/tasks/infos.yml

  "Ports-Demo":
    description: |
      This execution demonstrates the usage of the `ports` directive.  The
      output of `env | sort` shows the assigned port as the value of the given
      name.
    specification:
      name: Ports Demo
      _cider-ci_include: /.cider-ci/shared/defaults.yml
      tasks:
        _cider-ci_include: /.cider-ci/tasks/ports.yml

  "Result-Demo":
    description: |
      This execution creates the specially treated `result.json` file with
      `value`, and `summary` properties.  It also attaches the `result.json` by
      the `trial_attachments` directive. 
    specification:
      name: Result Demo
      _cider-ci_include: /.cider-ci/shared/defaults.yml
      tasks:
        _cider-ci_include: /.cider-ci/tasks/result.yml

  "Submodule-Demo":
    description: |
      This execution demonstrates  the usage of the `git_options`/`submodule`
      specification.  It also checks some properties of the checked out
      submodules and fails if they would not be present. 
    specification: 
      _cider-ci_include: /.cider-ci/shared/submodule_context.yml

  "Tests":
    description: >
      This executions runs several bash scripts. Some of them sleep for a
      while.  Some of them fail with a certain probability.  One of them
      combines both by using the `timeout` directive of a script.
    specification:
      _cider-ci_include: /.cider-ci/test_spec.yml

  "Trigger-Demo": 
    description: |
      This execution will be automatically run when a commit containing
      it becomes the head of a branch. 
      The `trigger` property accepts the same values as the `depends` property.
    trigger: 
      branch: '^master|wip.*$'
    specification: 
      name: Trigger-Demo
      _cider-ci_include: /.cider-ci/shared/sleeping_task_context.yml

