Ports-Demo:

  name: Ports Demo 

  description: This task demonstrates the `ports` property. 

  ports: 
    XVNC_PORT: 
      inet_address: "localhost"
      min: 5900
      max: 5999

  scripts:
    main:
      body: env | sort 

