jobs:
  attachments:
    name: Attachments Demo
    description: |
      This job demonstrates the usage of the `tree_attachments` and
      `trial_attachments` directive.  It creates files which are attached
      as tree- / trial-attachments respectively.

    context:

      tasks:

        attachments-demo:

          name: Attachments Demo

          traits:
            Bash: true

          trial_attachments:
            tmp-files:
              content_type: text/plain
              include_match: ^tmp\/.*trial.*\.txt$
            tmp-files-exact-match:
              content_type: text/plain
              include_match: ^tmp\/exact-matching-filename\.txt$

          tree_attachments:
            tmp-files:
              content_type: text/plain
              include_match: ^tmp\/.*tree.*\.txt$

          scripts:
            trial-attachment:
              body: |
                set -eux
                mkdir -p tmp
                echo 'I am a trial attachment!' > tmp/a-trial-attachment.txt
                echo 'I am another trial attachment!' > tmp/exact-matching-filename.txt
                touch tmp/null-trial-attachment.txt
            tree-attachment:
              body: >
                mkdir -p tmp &&
                echo 'I am a tree attachment!' > tmp/a-tree-attachment.txt

