jobs:

  dispatch-storm-delay:

    name: Dispatch-Storm Delay Demo
    description: |
      This job demonstrates the 'dispatch_storm_delay_duration' feature.

    context:

      task_defaults:
        max_trials: 1
        dispatch_storm_delay_duration: 20 Seconds
        traits:
          Bash: true
        scripts:
          main:
            body: sleep 30

      tasks:
        t1: {}
        t2: {}
