jobs:

  environment-variables:
    name: Environment Variables Demo
    description: |
      This job Demonstrates the usage of the `environment-variables` and
      `environment-variables_process-templates` directive.

      The _Set and Show_ subcontext demonstrates inheritance and runs
      some basic tests.

      The _Substitution_ subcontext demonstrates the usage of
      `environment-variables_process-templates`.

    context:

      task-defaults:
        environment-variables:
          CI_TASK_DEFAULTS: "Inherited!"
          SOME_DEFAULT: "X"
          THE_ANSWER: 42
        traits:
          bash: true


      subcontexts:

        set_and_show:

          name: Set and Show

          tasks:

            show_and_test:

              name: Set and Show Environment Variables

              scripts:

                show:
                  body: env | sort

                test-task-env-vars:
                  body: |
                    test ${THE_ANSWER} = "42"

                test-inheritance:
                  body: |
                    test ${SOME_DEFAULT} == "X"

                test-script-overrides:
                  environment-variables:
                    SOME_DEFAULT: "Y"
                  body: |
                    test ${SOME_DEFAULT} == "Y"


        substitution:

          name: Substitution

          tasks:

            enabled-substitution:
              name: "Enabled Substitution"
              script-defaults:
              scripts:
                substitute_ci_var:
                  environment-variables:
                    THE_SUBSTITUTED_ANSWER: "{{THE_ANSWER}}"
                  environment-variables_process-templates: true
                  body: |
                    test "${THE_SUBSTITUTED_ANSWER}" = 42

            recursive-substitution:
              name: "Recursive Substitution"
              ports:
                XVNC_PORT:
                  inet_address: "localhost"
                  min: 5900
                  max: 5999
              scripts:
                substitute_ci_var:
                  environment-variables:
                    T1: "{{T2}}"
                    T2: "{{T3}}"
                    T3: 7
                    P1: "{{XVNC_PORT}}"
                    P2: "{{P1}}"
                    P3: "{{P2}}"
                  environment-variables_process-templates: true
                  body: |
                    set -eux
                    test "${T1}" = 7
                    test "${P3}" = "${XVNC_PORT}"
                    test "${P3}_${T1}" = "${XVNC_PORT}_7"

            disabled-substitution:
              name: "Disabled Substitution"
              scripts:
                substitute_ci_var:
                  environment-variables:
                    THE_SUBSTITUTED_ANSWER: "{{THE_ANSWER}}"
                  body: |
                    test "${THE_SUBSTITUTED_ANSWER}" = '{{THE_ANSWER}}'


